# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: nova_site
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './docker/app/php.ini:/usr/local/etc/php/php.ini'
        networks:
            - nova_site
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - 'nova_site-mysql:/var/lib/mysql'
        networks:
            - nova_site
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - nova_site
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'
        networks:
            - nova_site
        depends_on:
            - app
        restart: unless-stopped
networks:
    nova_site:
        driver: bridge
volumes:
    nova_site-mysql:
        driver: local
